### ISSUE TITLE
Filter not working properly

### ISSUE THREAD

**Issue by kosbarts** [eweracs/remove-nested-components#1]
I am running the filter on export as a PreFilter in version 3.1.2 (3151) and it does remove some of the nested components but it's leaving some others (i.e. Greek letters, punctuation, fraction numerals).

**Comment by eweracs** [comment]
Hi, thanks for the report. Can you give some concrete examples? Before and after filter application? I have not ever encountered any issues, even with Components nested multiple times (such as in fractions). If you like, you can send me a sample file in which it doesn't work for you and I will be happy to take a look. You can find my email address on my website. Thanks!

**Comment by kosbarts** [comment]
Hi Sebastian.


I'll send you a file via email.

**Comment by eweracs** [comment]
Fixed in 7d8c2d1127901d5d71c66028277d2346862bae78.
